services:
  - type: web
    name: todo-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d38u87vfte5s73cdcd3g-a.render.com:5432/tododb_q0ws
      - key: SPRING_DATASOURCE_USERNAME
        value: aluno
      - key: SPRING_DATASOURCE_PASSWORD
        value: pFTSDlaeyuPoTrwhyVlgL2pQSDcfAYcB
